package com.odeal.vendingmachine.config;

public enum States {
    PRODUCT_SELECTION, QUANTITY_SELECTION, QUANTITY_SELECTED,SUGAR_SELECTION, WAITING_FOR_PAYMENT,
    CASH_RECEIVED,WAITING_FOR_MORE_CASH,
    PAYMENT_COMPLETE,REFUNDABLE, PRINTABLE,VOUCHER_PRINTED
}
